name:                sdl-apecs-ui
version:             0.1.0.0
github:              "Solonarv/sdl-apecs-ui"
license:             BSD3
author:              "Solonarv"
maintainer:          "nstamm@gmx.de"
copyright:           "2018 Solonarv"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A GUI library built on top of SDL and Apecs.
category:            UI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Solonarv/sdl-apecs-ui#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2 == 2.4.*
- sdl2-ttf == 2.0.*
- apecs == 0.2.*
- text == 1.2.*
- linear
- deepseq

library:
  source-dirs: src

tests:
  sdl-apecs-ui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdl-apecs-ui

default-extensions: &extensions
  - LambdaCase
  - PatternSynonyms
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveDataTypeable
  - ScopedTypeVariables
  - GADTs
  - TypeFamilies
  - RankNTypes
  - ViewPatterns
  - TypeApplications
  - MultiParamTypeClasses
  - FlexibleContexts
  - ConstraintKinds
  - TypeOperators
  - DataKinds